// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtRi3Z2G6dHNsBpLwidcV9mLohwK2-z0',
    appId: '1:523961680931:web:39b48b72652769f082dd96',
    messagingSenderId: '523961680931',
    projectId: 'faste-food-b70cf',
    authDomain: 'faste-food-b70cf.firebaseapp.com',
    storageBucket: 'faste-food-b70cf.firebasestorage.app',
    measurementId: 'G-DL98PSPLYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDE-C8S3l4RQxbDn4Auu_XehtKeC5v1r8',
    appId: '1:523961680931:android:adfcac4738e2c4ca82dd96',
    messagingSenderId: '523961680931',
    projectId: 'faste-food-b70cf',
    storageBucket: 'faste-food-b70cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YsZ0VAY2viOmUGtdOraBuf3R-VZLu8E',
    appId: '1:523961680931:ios:2ccaf99d3dc59eee82dd96',
    messagingSenderId: '523961680931',
    projectId: 'faste-food-b70cf',
    storageBucket: 'faste-food-b70cf.firebasestorage.app',
    iosBundleId: 'com.example.fastFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YsZ0VAY2viOmUGtdOraBuf3R-VZLu8E',
    appId: '1:523961680931:ios:2ccaf99d3dc59eee82dd96',
    messagingSenderId: '523961680931',
    projectId: 'faste-food-b70cf',
    storageBucket: 'faste-food-b70cf.firebasestorage.app',
    iosBundleId: 'com.example.fastFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtRi3Z2G6dHNsBpLwidcV9mLohwK2-z0',
    appId: '1:523961680931:web:5fabd7d81c9b861b82dd96',
    messagingSenderId: '523961680931',
    projectId: 'faste-food-b70cf',
    authDomain: 'faste-food-b70cf.firebaseapp.com',
    storageBucket: 'faste-food-b70cf.firebasestorage.app',
    measurementId: 'G-3B7RZZZ3S9',
  );
}
